services:
  kafka:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"

  main-db:
    image: postgres:latest
    container_name: main-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=Prod
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  config-server:
    build:
      context: .
      target: config-server
    ports:
      - "8888:8888"
    environment:
      SPRING_PROFILES_ACTIVE: git
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  discovery-service:
    build:
      context: .
      target: discovery-service
    ports:
      - "8761:8761"
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888

  gateway-service:
    build:
      context: .
      target: gateway-service
    ports:
      - "80:80"
    depends_on:
      - config-server
      - discovery-service
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
      eureka.client.serviceUrl.defaultZone: http://discovery-service:8761/eureka

  user-service:
    build:
      context: .
      target: user-service
    ports:
      - "8080:8080"
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      eureka.client.serviceUrl.defaultZone: http://discovery-service:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:postgresql://main-db:5432/Prod
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - config-server
      - discovery-service
      - kafka
      - main-db

  notification-service:
    build:
      context: .
      target: notification-service
    ports:
      - "8081:8081"
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      eureka.client.serviceUrl.defaultZone: http://discovery-service:8761/eureka
    depends_on:
      - config-server
      - discovery-service
      - kafka