server:
  port: 80

spring:
  application:
    name: gateway-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
  main:
    web-application-type: reactive